theme = "ayu_mirage"

[editor]
color-modes = true
completion-trigger-len = 1
completion-timeout = 100
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
rulers = [120]
true-color = true
trim-trailing-whitespace = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 30000

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",

]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
  "selections",
]
separator = "│"

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
